/*
Descripción: Vista del Menu Principal
Fecha: 12-agosto-2022
Nombre: Enzo Alejandro Maciel Núñez
 */
package Vista;

import Controlador.CRevisarAceptar;
import Modelo.MRevisarClientes;
import Modelo.MVentanaCotizaciones;
import Controlador.CRevisarClientes;
import Controlador.CVentanaCotizaciones;
import Controlador.CVentanaEvenSes;
import Modelo.MRevisarAceptar;
import Modelo.MVentanaEvenSes;


public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIrCLI = new javax.swing.JButton();
        btnIrSol = new javax.swing.JButton();
        btnIrCot = new javax.swing.JButton();
        btnIrES = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imgTitulo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(251, 235, 163));
        jPanel1.setToolTipText("");
        jPanel1.setMaximumSize(new java.awt.Dimension(880, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(880, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(880, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIrCLI.setBackground(new java.awt.Color(245, 206, 18));
        btnIrCLI.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        btnIrCLI.setText("Ir");
        btnIrCLI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrCLIActionPerformed(evt);
            }
        });
        jPanel1.add(btnIrCLI, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 160, -1));

        btnIrSol.setBackground(new java.awt.Color(245, 206, 18));
        btnIrSol.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        btnIrSol.setText("Ir");
        btnIrSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrSolActionPerformed(evt);
            }
        });
        jPanel1.add(btnIrSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 160, -1));

        btnIrCot.setBackground(new java.awt.Color(245, 206, 18));
        btnIrCot.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        btnIrCot.setText("Ir");
        btnIrCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrCotActionPerformed(evt);
            }
        });
        jPanel1.add(btnIrCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 150, -1));

        btnIrES.setBackground(new java.awt.Color(245, 206, 18));
        btnIrES.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        btnIrES.setText("Ir");
        btnIrES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrESActionPerformed(evt);
            }
        });
        jPanel1.add(btnIrES, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 160, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 0, 24)); // NOI18N
        jLabel1.setText("Menú Clientes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 0, 24)); // NOI18N
        jLabel2.setText("Menú Solicitudes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 0, 24)); // NOI18N
        jLabel3.setText("Menú Cotizaciones");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 0, 24)); // NOI18N
        jLabel4.setText("Menú Eventos y Sesiones");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        imgTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO - SOLO NOMBRE png.png"))); // NOI18N
        imgTitulo.setFocusable(false);
        imgTitulo.setInheritsPopupMenu(false);
        imgTitulo.setRequestFocusEnabled(false);
        imgTitulo.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(imgTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 460, 160));

        btnSalir.setBackground(new java.awt.Color(245, 206, 18));
        btnSalir.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, -1));

        jPanel2.setBackground(new java.awt.Color(213, 178, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 110, 500));

        jPanel3.setBackground(new java.awt.Color(213, 178, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 120, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrCLIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrCLIActionPerformed
        // TODO add your handling code here:
        MRevisarClientes modelo = new MRevisarClientes();
        RevisarClientes vista = new RevisarClientes();
        CRevisarClientes controlador1 = new CRevisarClientes(modelo, vista);
        controlador1.iniciarVista();
        this.dispose();
    }//GEN-LAST:event_btnIrCLIActionPerformed

    private void btnIrCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrCotActionPerformed
        // TODO add your handling code here:
        MVentanaCotizaciones modelo = new MVentanaCotizaciones();
        VVentanaCotizaciones vista = new VVentanaCotizaciones();
        CVentanaCotizaciones controlador3 = new CVentanaCotizaciones(modelo, vista);
        controlador3.iniciarVista();
        this.dispose();
    }//GEN-LAST:event_btnIrCotActionPerformed

    private void btnIrSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrSolActionPerformed
        // TODO add your handling code here:
        MRevisarAceptar modelo = new MRevisarAceptar();
        RevisarAceptar vista = new RevisarAceptar();
        CRevisarAceptar controlador2 = new CRevisarAceptar(modelo, vista);
        controlador2.iniciarVista();
        this.dispose();
    }//GEN-LAST:event_btnIrSolActionPerformed

    private void btnIrESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrESActionPerformed
        // TODO add your handling code here:
        MVentanaEvenSes modelo = new MVentanaEvenSes();
        VentanaEvenSes vista = new VentanaEvenSes();
        CVentanaEvenSes controlador4 = new CVentanaEvenSes(modelo, vista);
        controlador4.iniciarVista();
        this.dispose();
    }//GEN-LAST:event_btnIrESActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIrCLI;
    public javax.swing.JButton btnIrCot;
    public javax.swing.JButton btnIrES;
    public javax.swing.JButton btnIrSol;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel imgTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
