/*
Descripcion: Ventana para que trabajador revise solicitudes
Nombre: Halach Uinic Domínguez Sarabia
Fecha: 26-junio-2022
 */
package Vista;

public class RevisarAceptar extends javax.swing.JFrame {

    /**
     * Creates new form RevisarAceptar
     */
    public RevisarAceptar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEliminar43 = new javax.swing.JLabel();
        lblId43 = new javax.swing.JLabel();
        tfEliminar43 = new javax.swing.JTextField();
        btnEliminar43 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnRegresarRA = new javax.swing.JButton();
        tfBuscar44 = new javax.swing.JTextField();
        lblID44 = new javax.swing.JLabel();
        lblBuscar43 = new javax.swing.JLabel();
        btnBuscar44 = new javax.swing.JButton();
        JScrollLugares = new javax.swing.JScrollPane();
        tbLugares = new javax.swing.JTable();
        lblTitulo42 = new javax.swing.JLabel();
        btnEliminar44 = new javax.swing.JButton();
        tfEliminar44 = new javax.swing.JTextField();
        lblId44 = new javax.swing.JLabel();
        lblEliminar45 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        lblBuscar44 = new javax.swing.JLabel();
        tfNumPersonas46 = new javax.swing.JTextField();
        tfNumHoras46 = new javax.swing.JTextField();
        tfEOS46 = new javax.swing.JTextField();
        tfIDES46 = new javax.swing.JTextField();
        tfIDCliente46 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        calFecha45 = new com.toedter.calendar.JDateChooser();
        calFecha46 = new com.toedter.calendar.JDateChooser();
        calHora = new com.toedter.calendar.JDateChooser();
        calFechaSolicitud45 = new com.toedter.calendar.JDateChooser();
        calFechaSolicitud46 = new com.toedter.calendar.JDateChooser();
        tfEOS45 = new javax.swing.JTextField();
        tfIDCliente45 = new javax.swing.JTextField();
        tfIDLugar45 = new javax.swing.JTextField();
        tfNumHoras45 = new javax.swing.JTextField();
        tfNumPersonas45 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfInfoLugar45 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfIExtra45 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblBuscar45 = new javax.swing.JLabel();
        calHora2 = new com.toedter.calendar.JDateChooser();
        tfIDLugar46 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tfIExtra46 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tfInfoLugar46 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbSolicitudes43 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        lblEliminar43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEliminar43.setText("Eliminar");

        lblId43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblId43.setText("ID:");

        btnEliminar43.setText("Eliminar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Netpics Fotografía");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(251, 235, 163));
        jPanel2.setMaximumSize(new java.awt.Dimension(1300, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(1300, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(1300, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresarRA.setBackground(new java.awt.Color(245, 206, 18));
        btnRegresarRA.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        btnRegresarRA.setText("Regresar");
        btnRegresarRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarRAActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresarRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 690, 120, 40));

        tfBuscar44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscar44ActionPerformed(evt);
            }
        });
        jPanel2.add(tfBuscar44, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 91, -1));

        lblID44.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        lblID44.setText("IdSolicitud:");
        jPanel2.add(lblID44, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        lblBuscar43.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblBuscar43.setText("Buscar");
        jPanel2.add(lblBuscar43, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        btnBuscar44.setBackground(new java.awt.Color(245, 206, 18));
        btnBuscar44.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        btnBuscar44.setText("Buscar");
        btnBuscar44.setPreferredSize(new java.awt.Dimension(100, 30));
        btnBuscar44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar44ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar44, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        tbLugares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbLugares.getTableHeader().setReorderingAllowed(false);
        JScrollLugares.setViewportView(tbLugares);

        jPanel2.add(JScrollLugares, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 370, 220, 120));

        lblTitulo42.setFont(new java.awt.Font("Roboto Condensed", 1, 48)); // NOI18N
        lblTitulo42.setText("Ventana Solicitudes");
        jPanel2.add(lblTitulo42, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, 50));

        btnEliminar44.setBackground(new java.awt.Color(245, 206, 18));
        btnEliminar44.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        btnEliminar44.setText("Eliminar");
        jPanel2.add(btnEliminar44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, 106, 30));
        jPanel2.add(tfEliminar44, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 106, -1));

        lblId44.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        lblId44.setText("IdSolicitud:");
        jPanel2.add(lblId44, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, -1, -1));

        lblEliminar45.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblEliminar45.setText("Eliminar");
        jPanel2.add(lblEliminar45, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(245, 206, 18));
        btnAgregar.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 117, 35));

        lblBuscar44.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblBuscar44.setText("Agregar");
        jPanel2.add(lblBuscar44, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));
        jPanel2.add(tfNumPersonas46, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, 100, -1));
        jPanel2.add(tfNumHoras46, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 71, -1));
        jPanel2.add(tfEOS46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 74, -1));
        jPanel2.add(tfIDES46, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 88, -1));
        jPanel2.add(tfIDCliente46, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 80, -1));

        jLabel16.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel16.setText("Fecha Solicitud:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        jLabel18.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel18.setText("IdCliente:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, -1, -1));

        btnModificar.setBackground(new java.awt.Color(245, 206, 18));
        btnModificar.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 117, 38));

        jLabel20.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel20.setText("NumHoras:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, -1));

        jLabel21.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel21.setText("NumPersonas:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, -1, -1));

        jLabel22.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel22.setText("Fecha:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, -1, -1));

        calFecha45.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(calFecha45, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 97, -1));

        calFecha46.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(calFecha46, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, 103, -1));

        calHora.setDateFormatString("HH:mm:ss");
        jPanel2.add(calHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 100, -1));

        calFechaSolicitud45.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(calFechaSolicitud45, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 111, -1));

        calFechaSolicitud46.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(calFechaSolicitud46, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, 128, -1));
        jPanel2.add(tfEOS45, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 74, -1));
        jPanel2.add(tfIDCliente45, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 82, -1));
        jPanel2.add(tfIDLugar45, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 100, -1));
        jPanel2.add(tfNumHoras45, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 71, -1));
        jPanel2.add(tfNumPersonas45, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 100, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel2.setText("EvenOSes:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        tfInfoLugar45.setColumns(20);
        tfInfoLugar45.setRows(5);
        jScrollPane2.setViewportView(tfInfoLugar45);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 300, 90));

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel3.setText("Fecha:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel4.setText("Hora:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, -1, -1));

        tfIExtra45.setColumns(20);
        tfIExtra45.setRows(5);
        jScrollPane3.setViewportView(tfIExtra45);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 260, 90));

        jLabel5.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel5.setText("NumHoras:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel6.setText("NumPersonas:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel7.setText("Fecha Solicitud:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Tabla Lugares");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel9.setText("IdCliente:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel10.setText("Info Extra:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel11.setText("Info Lugar:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel12.setText("EvenOSes:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel13.setText("IdSolicitud:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));

        lblBuscar45.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblBuscar45.setText("Modificar");
        jPanel2.add(lblBuscar45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        calHora2.setDateFormatString("HH:mm:ss");
        jPanel2.add(calHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 100, -1));
        jPanel2.add(tfIDLugar46, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 100, -1));

        tfIExtra46.setColumns(20);
        tfIExtra46.setRows(5);
        jScrollPane4.setViewportView(tfIExtra46);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 260, 90));

        jLabel23.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel23.setText("Info Extra:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, -1, -1));

        jLabel25.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel25.setText("Info Lugar:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, -1, -1));

        tfInfoLugar46.setColumns(20);
        tfInfoLugar46.setRows(5);
        jScrollPane5.setViewportView(tfInfoLugar46);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 280, 100));

        jLabel19.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel19.setText("Hora:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, -1, -1));

        jLabel15.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel15.setText("Id Lugar:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO - SOLO FIGURA png.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(47, 47));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        tbSolicitudes43.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbSolicitudes43.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tbSolicitudes43);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1105, 135));

        jLabel14.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel14.setText("Id Lugar:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarRAActionPerformed

    private void tfBuscar44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscar44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscar44ActionPerformed

    private void btnBuscar44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar44ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevisarAceptar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevisarAceptar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevisarAceptar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevisarAceptar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevisarAceptar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollLugares;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnBuscar44;
    private javax.swing.JButton btnEliminar43;
    public javax.swing.JButton btnEliminar44;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnRegresarRA;
    public com.toedter.calendar.JDateChooser calFecha45;
    public com.toedter.calendar.JDateChooser calFecha46;
    public com.toedter.calendar.JDateChooser calFechaSolicitud45;
    public com.toedter.calendar.JDateChooser calFechaSolicitud46;
    public com.toedter.calendar.JDateChooser calHora;
    public com.toedter.calendar.JDateChooser calHora2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblBuscar43;
    private javax.swing.JLabel lblBuscar44;
    private javax.swing.JLabel lblBuscar45;
    private javax.swing.JLabel lblEliminar43;
    private javax.swing.JLabel lblEliminar45;
    private javax.swing.JLabel lblID44;
    private javax.swing.JLabel lblId43;
    private javax.swing.JLabel lblId44;
    private javax.swing.JLabel lblTitulo42;
    public javax.swing.JTable tbLugares;
    public javax.swing.JTable tbSolicitudes43;
    public javax.swing.JTextField tfBuscar44;
    public javax.swing.JTextField tfEOS45;
    public javax.swing.JTextField tfEOS46;
    private javax.swing.JTextField tfEliminar43;
    public javax.swing.JTextField tfEliminar44;
    public javax.swing.JTextField tfIDCliente45;
    public javax.swing.JTextField tfIDCliente46;
    public javax.swing.JTextField tfIDES46;
    public javax.swing.JTextField tfIDLugar45;
    public javax.swing.JTextField tfIDLugar46;
    public javax.swing.JTextArea tfIExtra45;
    public javax.swing.JTextArea tfIExtra46;
    public javax.swing.JTextArea tfInfoLugar45;
    public javax.swing.JTextArea tfInfoLugar46;
    public javax.swing.JTextField tfNumHoras45;
    public javax.swing.JTextField tfNumHoras46;
    public javax.swing.JTextField tfNumPersonas45;
    public javax.swing.JTextField tfNumPersonas46;
    // End of variables declaration//GEN-END:variables
}
