/*
Descripción: Vista del Menu EventoSesion
Fecha: 12-agosto-2022
Nombre: Halach Uinic Dominguez Sarabia
 */
package Vista;

/**
 *
 * @author halach
 */
public class VentanaEvenSes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEvenSes
     */
    public VentanaEvenSes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEOS44 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabDatosES = new javax.swing.JTable();
        lblBuscar44 = new javax.swing.JLabel();
        lblEliminar44 = new javax.swing.JLabel();
        tfEliminarES = new javax.swing.JTextField();
        tfBuscarES = new javax.swing.JTextField();
        btnBuscarES = new javax.swing.JButton();
        btnEliminarES = new javax.swing.JButton();
        lblId44 = new javax.swing.JLabel();
        lblID44 = new javax.swing.JLabel();
        tfAEstadoES = new javax.swing.JTextField();
        lblRliquidado45 = new javax.swing.JLabel();
        lblLiquidacion45 = new javax.swing.JLabel();
        tfANumPersonasES = new javax.swing.JTextField();
        tfMHorasES = new javax.swing.JTextField();
        tfANhorasES = new javax.swing.JTextField();
        tfMIdcotES = new javax.swing.JTextField();
        lblEstado45 = new javax.swing.JLabel();
        lblPersonas45 = new javax.swing.JLabel();
        lblModificar43 = new javax.swing.JLabel();
        tfARliquidadoES = new javax.swing.JTextField();
        tfAGananciaES = new javax.swing.JTextField();
        lblModificar44 = new javax.swing.JLabel();
        tfModificarES = new javax.swing.JTextField();
        lblGanancia45 = new javax.swing.JLabel();
        btnAgregarES = new javax.swing.JButton();
        lblHora44 = new javax.swing.JLabel();
        lblIDES44 = new javax.swing.JLabel();
        tfMGananciaES = new javax.swing.JTextField();
        lblFecha44 = new javax.swing.JLabel();
        lblIDC44 = new javax.swing.JLabel();
        tfMNumPersonasES = new javax.swing.JTextField();
        tfMEstadoES = new javax.swing.JTextField();
        tfMRliquidadoES = new javax.swing.JTextField();
        tfMLocacionES = new javax.swing.JTextField();
        btnRegresarES = new javax.swing.JButton();
        btnModificarES = new javax.swing.JButton();
        lblGanancia44 = new javax.swing.JLabel();
        lblLocacion44 = new javax.swing.JLabel();
        lblHoras44 = new javax.swing.JLabel();
        lblLiquidacion44 = new javax.swing.JLabel();
        lblRliquidado44 = new javax.swing.JLabel();
        lblPersonas44 = new javax.swing.JLabel();
        lblEstado44 = new javax.swing.JLabel();
        tfALocacionES = new javax.swing.JTextField();
        lblLocacion45 = new javax.swing.JLabel();
        lblHoras45 = new javax.swing.JLabel();
        lblIDC45 = new javax.swing.JLabel();
        tfAIdcotES = new javax.swing.JTextField();
        lblFecha45 = new javax.swing.JLabel();
        lblHora45 = new javax.swing.JLabel();
        MfechaCalES = new com.toedter.calendar.JDateChooser();
        MfechaliqES = new com.toedter.calendar.JDateChooser();
        AFechaES = new com.toedter.calendar.JDateChooser();
        AFechaliqES = new com.toedter.calendar.JDateChooser();
        calHORA = new com.toedter.calendar.JDateChooser();
        calHORA2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(251, 235, 163));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 600));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEOS44.setFont(new java.awt.Font("Roboto Condensed", 1, 48)); // NOI18N
        lblEOS44.setText("Agenda de eventos y sesiones");
        jPanel1.add(lblEOS44, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 50));

        tabDatosES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabDatosES.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabDatosES);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 1125, 107));

        lblBuscar44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBuscar44.setText("Buscar");
        jPanel1.add(lblBuscar44, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        lblEliminar44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEliminar44.setText("Eliminar");
        jPanel1.add(lblEliminar44, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, -1, -1));
        jPanel1.add(tfEliminarES, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 101, -1));

        tfBuscarES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarESActionPerformed(evt);
            }
        });
        jPanel1.add(tfBuscarES, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 91, -1));

        btnBuscarES.setBackground(new java.awt.Color(245, 206, 18));
        btnBuscarES.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnBuscarES.setText("Buscar");
        btnBuscarES.setPreferredSize(new java.awt.Dimension(100, 30));
        btnBuscarES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarESActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarES, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 110, -1));

        btnEliminarES.setBackground(new java.awt.Color(245, 206, 18));
        btnEliminarES.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnEliminarES.setText("Eliminar");
        btnEliminarES.setMaximumSize(new java.awt.Dimension(100, 30));
        btnEliminarES.setMinimumSize(new java.awt.Dimension(100, 30));
        btnEliminarES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarESActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarES, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 110, 32));

        lblId44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblId44.setText("IdEventoSesion:");
        jPanel1.add(lblId44, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        lblID44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblID44.setText("IdEventoSesion:");
        jPanel1.add(lblID44, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));
        jPanel1.add(tfAEstadoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 76, -1));

        lblRliquidado45.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblRliquidado45.setText("RestanteALiquidar:");
        jPanel1.add(lblRliquidado45, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        lblLiquidacion45.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblLiquidacion45.setText("Fechaliquidacion:");
        jPanel1.add(lblLiquidacion45, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));
        jPanel1.add(tfANumPersonasES, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 81, -1));
        jPanel1.add(tfMHorasES, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 83, -1));
        jPanel1.add(tfANhorasES, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 90, -1));
        jPanel1.add(tfMIdcotES, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 74, -1));

        lblEstado45.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblEstado45.setText("Estado:");
        jPanel1.add(lblEstado45, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        lblPersonas45.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblPersonas45.setText("NumPersonas:");
        jPanel1.add(lblPersonas45, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        lblModificar43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblModificar43.setText("Modificar");
        jPanel1.add(lblModificar43, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));
        jPanel1.add(tfARliquidadoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 70, -1));
        jPanel1.add(tfAGananciaES, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 350, 67, -1));

        lblModificar44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblModificar44.setText("Agregar");
        jPanel1.add(lblModificar44, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        tfModificarES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModificarESActionPerformed(evt);
            }
        });
        jPanel1.add(tfModificarES, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 69, -1));

        lblGanancia45.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblGanancia45.setText("Ganancia:");
        jPanel1.add(lblGanancia45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 330, -1, -1));

        btnAgregarES.setBackground(new java.awt.Color(245, 206, 18));
        btnAgregarES.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnAgregarES.setText("Agregar");
        btnAgregarES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarESActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarES, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 110, -1));

        lblHora44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblHora44.setText("Hora:");
        jPanel1.add(lblHora44, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, -1, -1));

        lblIDES44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblIDES44.setText("IdEventoSesion:");
        jPanel1.add(lblIDES44, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));
        jPanel1.add(tfMGananciaES, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 460, 67, -1));

        lblFecha44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblFecha44.setText("Fecha:");
        jPanel1.add(lblFecha44, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, -1, -1));

        lblIDC44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblIDC44.setText("IdCotizacion:");
        jPanel1.add(lblIDC44, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));
        jPanel1.add(tfMNumPersonasES, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 81, -1));
        jPanel1.add(tfMEstadoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 76, -1));
        jPanel1.add(tfMRliquidadoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 70, -1));
        jPanel1.add(tfMLocacionES, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, 71, -1));

        btnRegresarES.setBackground(new java.awt.Color(245, 206, 18));
        btnRegresarES.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegresarES.setText("Regresar");
        btnRegresarES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarESActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarES, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 520, 138, 44));

        btnModificarES.setBackground(new java.awt.Color(245, 206, 18));
        btnModificarES.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnModificarES.setText("Modificar");
        btnModificarES.setMaximumSize(new java.awt.Dimension(100, 30));
        btnModificarES.setMinimumSize(new java.awt.Dimension(100, 30));
        btnModificarES.setPreferredSize(new java.awt.Dimension(100, 30));
        btnModificarES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarESActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarES, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 110, 26));

        lblGanancia44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblGanancia44.setText("Ganancia:");
        jPanel1.add(lblGanancia44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 440, -1, -1));

        lblLocacion44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblLocacion44.setText("Locacion");
        jPanel1.add(lblLocacion44, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, -1, -1));

        lblHoras44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblHoras44.setText("NumHoras:");
        jPanel1.add(lblHoras44, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));

        lblLiquidacion44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblLiquidacion44.setText("Fechaliquidacion:");
        jPanel1.add(lblLiquidacion44, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        lblRliquidado44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblRliquidado44.setText("RestanteALiquidar:");
        jPanel1.add(lblRliquidado44, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        lblPersonas44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblPersonas44.setText("NumPersonas:");
        jPanel1.add(lblPersonas44, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

        lblEstado44.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblEstado44.setText("Estado:");
        jPanel1.add(lblEstado44, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));
        jPanel1.add(tfALocacionES, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, 71, -1));

        lblLocacion45.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblLocacion45.setText("Locacion");
        jPanel1.add(lblLocacion45, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 330, -1, -1));

        lblHoras45.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblHoras45.setText("NumHoras:");
        jPanel1.add(lblHoras45, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        lblIDC45.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblIDC45.setText("IdCotizacion:");
        jPanel1.add(lblIDC45, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        tfAIdcotES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAIdcotESActionPerformed(evt);
            }
        });
        jPanel1.add(tfAIdcotES, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 74, -1));

        lblFecha45.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblFecha45.setText("Fecha:");
        jPanel1.add(lblFecha45, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, -1, -1));

        lblHora45.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        lblHora45.setText("Hora:");
        jPanel1.add(lblHora45, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, -1, -1));

        MfechaCalES.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(MfechaCalES, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, -1, -1));

        MfechaliqES.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(MfechaliqES, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, -1));

        AFechaES.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(AFechaES, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, -1, -1));

        AFechaliqES.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(AFechaliqES, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        calHORA.setDateFormatString("HH:mm:ss");
        jPanel1.add(calHORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, -1, -1));

        calHORA2.setDateFormatString("HH:mm:ss");
        jPanel1.add(calHORA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO - SOLO FIGURA png.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(47, 47));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBuscarESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarESActionPerformed

    private void btnBuscarESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarESActionPerformed

    private void btnEliminarESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarESActionPerformed

    }//GEN-LAST:event_btnEliminarESActionPerformed

    private void tfModificarESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModificarESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfModificarESActionPerformed

    private void btnAgregarESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarESActionPerformed

    }//GEN-LAST:event_btnAgregarESActionPerformed

    private void btnModificarESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarESActionPerformed

    }//GEN-LAST:event_btnModificarESActionPerformed

    private void btnRegresarESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarESActionPerformed

    private void tfAIdcotESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAIdcotESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAIdcotESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
 btnRegresarES      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEvenSes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEvenSes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEvenSes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEvenSes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEvenSes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser AFechaES;
    public com.toedter.calendar.JDateChooser AFechaliqES;
    public com.toedter.calendar.JDateChooser MfechaCalES;
    public com.toedter.calendar.JDateChooser MfechaliqES;
    public javax.swing.JButton btnAgregarES;
    public javax.swing.JButton btnBuscarES;
    public javax.swing.JButton btnEliminarES;
    public javax.swing.JButton btnModificarES;
    public javax.swing.JButton btnRegresarES;
    public com.toedter.calendar.JDateChooser calHORA;
    public com.toedter.calendar.JDateChooser calHORA2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar44;
    private javax.swing.JLabel lblEOS44;
    private javax.swing.JLabel lblEliminar44;
    private javax.swing.JLabel lblEstado44;
    private javax.swing.JLabel lblEstado45;
    private javax.swing.JLabel lblFecha44;
    private javax.swing.JLabel lblFecha45;
    private javax.swing.JLabel lblGanancia44;
    private javax.swing.JLabel lblGanancia45;
    private javax.swing.JLabel lblHora44;
    private javax.swing.JLabel lblHora45;
    private javax.swing.JLabel lblHoras44;
    private javax.swing.JLabel lblHoras45;
    private javax.swing.JLabel lblID44;
    private javax.swing.JLabel lblIDC44;
    private javax.swing.JLabel lblIDC45;
    private javax.swing.JLabel lblIDES44;
    private javax.swing.JLabel lblId44;
    private javax.swing.JLabel lblLiquidacion44;
    private javax.swing.JLabel lblLiquidacion45;
    private javax.swing.JLabel lblLocacion44;
    private javax.swing.JLabel lblLocacion45;
    private javax.swing.JLabel lblModificar43;
    private javax.swing.JLabel lblModificar44;
    private javax.swing.JLabel lblPersonas44;
    private javax.swing.JLabel lblPersonas45;
    private javax.swing.JLabel lblRliquidado44;
    private javax.swing.JLabel lblRliquidado45;
    public javax.swing.JTable tabDatosES;
    public javax.swing.JTextField tfAEstadoES;
    public javax.swing.JTextField tfAGananciaES;
    public javax.swing.JTextField tfAIdcotES;
    public javax.swing.JTextField tfALocacionES;
    public javax.swing.JTextField tfANhorasES;
    public javax.swing.JTextField tfANumPersonasES;
    public javax.swing.JTextField tfARliquidadoES;
    public javax.swing.JTextField tfBuscarES;
    public javax.swing.JTextField tfEliminarES;
    public javax.swing.JTextField tfMEstadoES;
    public javax.swing.JTextField tfMGananciaES;
    public javax.swing.JTextField tfMHorasES;
    public javax.swing.JTextField tfMIdcotES;
    public javax.swing.JTextField tfMLocacionES;
    public javax.swing.JTextField tfMNumPersonasES;
    public javax.swing.JTextField tfMRliquidadoES;
    public javax.swing.JTextField tfModificarES;
    // End of variables declaration//GEN-END:variables
}
