/*
Descripcion: Ventana para que ver todas las cotizaciones
Nombre: Halach
Fecha: 08-agosto-2022
 */
package Vista;

public class VVentanaCotizaciones extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCotizaciones
     */
    public VVentanaCotizaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblID43 = new javax.swing.JLabel();
        tfBuscarCot = new javax.swing.JTextField();
        btnBuscarCot = new javax.swing.JButton();
        lblBuscar43 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabDatosCot = new javax.swing.JTable();
        lblCotizaciones43 = new javax.swing.JLabel();
        tfEliminarCot = new javax.swing.JTextField();
        btnEliminarCot = new javax.swing.JButton();
        lblId43 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblEliminar43 = new javax.swing.JLabel();
        btnCotizarCot = new javax.swing.JButton();
        tfCotizarCot = new javax.swing.JTextField();
        lblEliminar44 = new javax.swing.JLabel();
        lblModificar44 = new javax.swing.JLabel();
        btnAgregarCot = new javax.swing.JToggleButton();
        calLimiteCot2 = new com.toedter.calendar.JDateChooser();
        tfIDSCot = new javax.swing.JTextField();
        tfEOSCot = new javax.swing.JTextField();
        tfTipoCot = new javax.swing.JTextField();
        tfAnticipoPromCot = new javax.swing.JTextField();
        tfAnticipoCot = new javax.swing.JTextField();
        tfEACot = new javax.swing.JTextField();
        tfTPCot = new javax.swing.JTextField();
        lblIDS43 = new javax.swing.JLabel();
        lblEOS43 = new javax.swing.JLabel();
        lblTipo43 = new javax.swing.JLabel();
        lblLocacion43 = new javax.swing.JLabel();
        lblAnticipo43 = new javax.swing.JLabel();
        lblEA43 = new javax.swing.JLabel();
        lblEAP43 = new javax.swing.JLabel();
        lblFP43 = new javax.swing.JLabel();
        lblModificar43 = new javax.swing.JLabel();
        lbliD44 = new javax.swing.JLabel();
        tfModificarCot = new javax.swing.JTextField();
        btnModificarCot = new javax.swing.JButton();
        tfTPCot2 = new javax.swing.JTextField();
        tfEACot2 = new javax.swing.JTextField();
        lblFP44 = new javax.swing.JLabel();
        lblEAP44 = new javax.swing.JLabel();
        lblEA44 = new javax.swing.JLabel();
        lblLocacion44 = new javax.swing.JLabel();
        calLimiteCot = new com.toedter.calendar.JDateChooser();
        btnRegresarCot = new javax.swing.JButton();
        tfAnticipoPromCot2 = new javax.swing.JTextField();
        tfAnticipoCot2 = new javax.swing.JTextField();
        lblAnticipo44 = new javax.swing.JLabel();
        tfTipoCot2 = new javax.swing.JTextField();
        lblTipo44 = new javax.swing.JLabel();
        tfEOSCot2 = new javax.swing.JTextField();
        lblEOS44 = new javax.swing.JLabel();
        tfIDSCot2 = new javax.swing.JTextField();
        lblIDS44 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(251, 235, 163));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID43.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblID43.setText("IdCotizacion:");
        jPanel1.add(lblID43, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 244, -1, -1));

        tfBuscarCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarCotActionPerformed(evt);
            }
        });
        jPanel1.add(tfBuscarCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 242, 94, -1));

        btnBuscarCot.setBackground(new java.awt.Color(245, 206, 18));
        btnBuscarCot.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        btnBuscarCot.setText("Buscar");
        jPanel1.add(btnBuscarCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        lblBuscar43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBuscar43.setText("Buscar");
        jPanel1.add(lblBuscar43, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 209, -1, -1));

        TabDatosCot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabDatosCot.setRowSelectionAllowed(false);
        TabDatosCot.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TabDatosCot);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 1071, 110));

        lblCotizaciones43.setFont(new java.awt.Font("Roboto Condensed", 1, 48)); // NOI18N
        lblCotizaciones43.setText("Cotizaciones");
        jPanel1.add(lblCotizaciones43, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));
        jPanel1.add(tfEliminarCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 242, 106, -1));

        btnEliminarCot.setBackground(new java.awt.Color(245, 206, 18));
        btnEliminarCot.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        btnEliminarCot.setText("Eliminar");
        jPanel1.add(btnEliminarCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        lblId43.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblId43.setText("IdCotizacion:");
        jPanel1.add(lblId43, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 244, -1, -1));

        jLabel24.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel24.setText("IdSolicitud:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, -1));

        lblEliminar43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEliminar43.setText("Eliminar");
        jPanel1.add(lblEliminar43, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        btnCotizarCot.setBackground(new java.awt.Color(245, 206, 18));
        btnCotizarCot.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        btnCotizarCot.setText("Cotizar");
        jPanel1.add(btnCotizarCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 93, 30));

        tfCotizarCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCotizarCotActionPerformed(evt);
            }
        });
        jPanel1.add(tfCotizarCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 82, -1));

        lblEliminar44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEliminar44.setText("Cotizar");
        jPanel1.add(lblEliminar44, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, -1, -1));

        lblModificar44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblModificar44.setText("Agregar");
        jPanel1.add(lblModificar44, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 312, -1, -1));

        btnAgregarCot.setBackground(new java.awt.Color(245, 206, 18));
        btnAgregarCot.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        btnAgregarCot.setText("Agregar");
        btnAgregarCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCotActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        calLimiteCot2.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(calLimiteCot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, 127, -1));
        jPanel1.add(tfIDSCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 76, -1));
        jPanel1.add(tfEOSCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 76, -1));
        jPanel1.add(tfTipoCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 74, -1));
        jPanel1.add(tfAnticipoPromCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 76, -1));
        jPanel1.add(tfAnticipoCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 73, -1));
        jPanel1.add(tfEACot, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 76, -1));
        jPanel1.add(tfTPCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 74, -1));

        lblIDS43.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblIDS43.setText("IdSolicitud:");
        jPanel1.add(lblIDS43, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        lblEOS43.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblEOS43.setText("EventoOsesion:");
        jPanel1.add(lblEOS43, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        lblTipo43.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblTipo43.setText("Tipo:");
        jPanel1.add(lblTipo43, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        lblLocacion43.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblLocacion43.setText("AnticipoProm:");
        jPanel1.add(lblLocacion43, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        lblAnticipo43.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblAnticipo43.setText("Anticipo:");
        jPanel1.add(lblAnticipo43, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        lblEA43.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblEA43.setText("EstadoAnticipo:");
        jPanel1.add(lblEA43, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        lblEAP43.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblEAP43.setText("EstadoAnticipoProm:");
        jPanel1.add(lblEAP43, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, -1, -1));

        lblFP43.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblFP43.setText("FechalimProm:");
        jPanel1.add(lblFP43, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 370, -1, -1));

        lblModificar43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblModificar43.setText("Modificar");
        jPanel1.add(lblModificar43, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 446, -1, -1));

        lbliD44.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lbliD44.setText("IdCotizacion:");
        jPanel1.add(lbliD44, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 452, -1, -1));
        jPanel1.add(tfModificarCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 450, 110, -1));

        btnModificarCot.setBackground(new java.awt.Color(245, 206, 18));
        btnModificarCot.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        btnModificarCot.setText("Modificar");
        jPanel1.add(btnModificarCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 446, -1, -1));
        jPanel1.add(tfTPCot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 74, -1));
        jPanel1.add(tfEACot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 509, 76, -1));

        lblFP44.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblFP44.setText("FechalimProm:");
        jPanel1.add(lblFP44, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, -1, -1));

        lblEAP44.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblEAP44.setText("EstadoAnticipoProm:");
        jPanel1.add(lblEAP44, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, -1, -1));

        lblEA44.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblEA44.setText("EstadoAnticipo:");
        jPanel1.add(lblEA44, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 489, -1, -1));

        lblLocacion44.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblLocacion44.setText("AnticipoProm:");
        jPanel1.add(lblLocacion44, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, -1, -1));

        calLimiteCot.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(calLimiteCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 127, -1));

        btnRegresarCot.setBackground(new java.awt.Color(245, 206, 18));
        btnRegresarCot.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        btnRegresarCot.setText("Regresar");
        jPanel1.add(btnRegresarCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 550, 120, 40));
        jPanel1.add(tfAnticipoPromCot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 76, -1));
        jPanel1.add(tfAnticipoCot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 509, 73, -1));

        lblAnticipo44.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblAnticipo44.setText("Anticipo:");
        jPanel1.add(lblAnticipo44, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 489, -1, -1));
        jPanel1.add(tfTipoCot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 509, 74, -1));

        lblTipo44.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblTipo44.setText("Tipo:");
        jPanel1.add(lblTipo44, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 489, -1, -1));
        jPanel1.add(tfEOSCot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 509, 76, -1));

        lblEOS44.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblEOS44.setText("EventoOsesion:");
        jPanel1.add(lblEOS44, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 489, -1, -1));
        jPanel1.add(tfIDSCot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 509, 76, -1));

        lblIDS44.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        lblIDS44.setText("IdSolicitud:");
        jPanel1.add(lblIDS44, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 489, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO - SOLO FIGURA png.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(47, 47));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1335, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBuscarCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarCotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarCotActionPerformed

    private void btnAgregarCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarCotActionPerformed

    private void tfCotizarCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCotizarCotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCotizarCotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVentanaCotizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVentanaCotizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVentanaCotizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVentanaCotizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VVentanaCotizaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TabDatosCot;
    public javax.swing.JToggleButton btnAgregarCot;
    public javax.swing.JButton btnBuscarCot;
    public javax.swing.JButton btnCotizarCot;
    public javax.swing.JButton btnEliminarCot;
    public javax.swing.JButton btnModificarCot;
    public javax.swing.JButton btnRegresarCot;
    public com.toedter.calendar.JDateChooser calLimiteCot;
    public com.toedter.calendar.JDateChooser calLimiteCot2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnticipo43;
    private javax.swing.JLabel lblAnticipo44;
    private javax.swing.JLabel lblBuscar43;
    private javax.swing.JLabel lblCotizaciones43;
    private javax.swing.JLabel lblEA43;
    private javax.swing.JLabel lblEA44;
    private javax.swing.JLabel lblEAP43;
    private javax.swing.JLabel lblEAP44;
    private javax.swing.JLabel lblEOS43;
    private javax.swing.JLabel lblEOS44;
    private javax.swing.JLabel lblEliminar43;
    private javax.swing.JLabel lblEliminar44;
    private javax.swing.JLabel lblFP43;
    private javax.swing.JLabel lblFP44;
    private javax.swing.JLabel lblID43;
    private javax.swing.JLabel lblIDS43;
    private javax.swing.JLabel lblIDS44;
    private javax.swing.JLabel lblId43;
    private javax.swing.JLabel lblLocacion43;
    private javax.swing.JLabel lblLocacion44;
    private javax.swing.JLabel lblModificar43;
    private javax.swing.JLabel lblModificar44;
    private javax.swing.JLabel lblTipo43;
    private javax.swing.JLabel lblTipo44;
    private javax.swing.JLabel lbliD44;
    public javax.swing.JTextField tfAnticipoCot;
    public javax.swing.JTextField tfAnticipoCot2;
    public javax.swing.JTextField tfAnticipoPromCot;
    public javax.swing.JTextField tfAnticipoPromCot2;
    public javax.swing.JTextField tfBuscarCot;
    public javax.swing.JTextField tfCotizarCot;
    public javax.swing.JTextField tfEACot;
    public javax.swing.JTextField tfEACot2;
    public javax.swing.JTextField tfEOSCot;
    public javax.swing.JTextField tfEOSCot2;
    public javax.swing.JTextField tfEliminarCot;
    public javax.swing.JTextField tfIDSCot;
    public javax.swing.JTextField tfIDSCot2;
    public javax.swing.JTextField tfModificarCot;
    public javax.swing.JTextField tfTPCot;
    public javax.swing.JTextField tfTPCot2;
    public javax.swing.JTextField tfTipoCot;
    public javax.swing.JTextField tfTipoCot2;
    // End of variables declaration//GEN-END:variables

    public class tModificarCot {

        public tModificarCot() {
        }
    }
}
